"""Initial database schema

Revision ID: f6d9997b391f
Revises: 
Create Date: 2026-09-22 10:46:08.568010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d9997b391f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('CV', 'PAST_PROJECT', 'TOOL_STACK', name='assettype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_assets_id'), 'internal_assets', ['id'], unique=False)
    op.create_index(op.f('ix_internal_assets_qdrant_point_id'), 'internal_assets', ['qdrant_point_id'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'RESEARCHING', 'RESEARCHED', 'GENERATING_PROPOSAL', 'PROPOSAL_READY', 'FAILED', name='tenderstatus'), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_id'), 'tenders', ['id'], unique=False)
    op.create_index(op.f('ix_tenders_title'), 'tenders', ['title'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('coverage_score_matrix', sa.JSON(), nullable=True),
    sa.Column('file_path_pptx', sa.String(length=500), nullable=True),
    sa.Column('file_path_pdf', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_table('prospect_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=150), nullable=True),
    sa.Column('estimated_revenue', sa.String(length=100), nullable=True),
    sa.Column('key_partners', sa.JSON(), nullable=True),
    sa.Column('domain_requirements', sa.JSON(), nullable=True),
    sa.Column('competitor_insights', sa.JSON(), nullable=True),
    sa.Column('estimated_budget_range', sa.String(length=100), nullable=True),
    sa.Column('raw_research_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id')
    )
    op.create_index(op.f('ix_prospect_research_id'), 'prospect_research', ['id'], unique=False)
    op.create_table('tender_asset_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['internal_assets.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_asset_matches_id'), 'tender_asset_matches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_asset_matches_id'), table_name='tender_asset_matches')
    op.drop_table('tender_asset_matches')
    op.drop_index(op.f('ix_prospect_research_id'), table_name='prospect_research')
    op.drop_table('prospect_research')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_tenders_title'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_internal_assets_qdrant_point_id'), table_name='internal_assets')
    op.drop_index(op.f('ix_internal_assets_id'), table_name='internal_assets')
    op.drop_table('internal_assets')
    # ### end Alembic commands ###
