# -*- coding: utf-8 -*-
"""scraper-v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pkmu4Q2pGkxxafoDZopPrhiFq3pg8y-8
"""

# =====================================================================
# CSTAM 3.0 x OliveSoft - Lead & Tender Detection Engine (MVP, ONE cell)
# Sources : HAICOP (marchespublics.gov.tn) + appeloffres.com
# Outputs : offers_combined.json / .csv / offers_report.pdf / offers_quality_report.json
#
# Cahier des charges covered
#   Detection engine ....... 2 public portals, dedup, fuzzy cross-portal link, is_new tracking
#   RAG-ready output ....... rag_query, requirements[], doc_excerpt, segment, skills_detected
#   Edge cases ............. missing_fields, quality_flags, expired (Tunis time), Arabic titles,
#                            truncated titles, placeholder references, blocked source = skipped
#   n8n .................... --webhook URL posts the new leads (JSON) to an n8n Webhook node
#   Dashboard .............. lead_score (0-100), priority (hot/warm/cold), urgent, days_left
#   Proposal generation .... offers_report.pdf keeps the sample_rfp_fr.pdf layout
#   Bonus multi-source ..... two portals crawled and merged
#
# HOW TO RUN
#   Colab: paste this whole file in ONE cell and run it. To change options, edit RUN_ARGS below.
#   Terminal: python cstam_pipeline.py --min-fit medium
#   No internet / blocked portals: RUN_ARGS = "--demo" (clearly-labelled simulated tenders)
# =====================================================================
RUN_ARGS = ""      # examples: "--min-fit medium"  |  "--enrich --max-tenders 120"  |  "--demo"

import sys
import subprocess
import importlib


def _ensure(pkgs):
    for mod, pkg in pkgs:
        try:
            importlib.import_module(mod)
        except ImportError:
            subprocess.run([sys.executable, "-m", "pip", "install", "-q", pkg], check=False)


_ensure([("requests", "requests"), ("bs4", "beautifulsoup4"), ("lxml", "lxml"), ("pandas", "pandas"),
         ("reportlab", "reportlab"), ("pypdf", "pypdf"), ("playwright", "playwright")])

import os
import re
import io
import json
import html
import time
import shlex
import random
import shutil
import zipfile
import tempfile
import argparse
import traceback
import unicodedata
import urllib.robotparser as robotparser
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone, timedelta
from difflib import SequenceMatcher
from urllib.parse import urljoin, urlparse
from xml.sax.saxutils import escape as xml_escape

import requests
import pandas as pd
from bs4 import BeautifulSoup

try:
    from zoneinfo import ZoneInfo
    TUNIS = ZoneInfo("Africa/Tunis")
except Exception:
    TUNIS = timezone(timedelta(hours=1))            # Tunisia: UTC+1, no DST

# ---------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------
BASE_HC = "https://www.marchespublics.gov.tn"
LIST_URL = f"{BASE_HC}/fr/appels-doffres"
TENDER_RE = re.compile(r"(Tender-\d+)")
BASE_AO = "https://www.appeloffres.com"
AO_CATEGORIES = {"informatique-materiels-et-logiciels": "Informatique matériels et logiciels", "telecom": "Télécom"}
UA = "OliveSoft-RFP-Intelligence/1.0 (+CSTAM 3.0 hackathon)"
BROWSER_UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
              "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36")
REQUEST_TIMEOUT, MAX_RETRIES, RESPECT_ROBOTS = 25, 3, True
HC_MIN_SCORE, AO_MIN_SCORE = 2, 1
MAX_DOCS_PER_TENDER, MAX_DOC_BYTES = 3, 15 * 1024 * 1024
ARABIC_RE = re.compile(r"[\u0600-\u06FF\u0750-\u077F\uFB50-\uFDFF\uFE70-\uFEFF]+")
_HERE = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else "."


# ---------------------------------------------------------------------
# TEXT UTILS
# ---------------------------------------------------------------------
def strip_accents(s):
    s = unicodedata.normalize("NFKD", (s or "").replace("’", "'").replace("‘", "'"))
    return "".join(c for c in s if not unicodedata.combining(c)).lower()


def clean(s):
    return re.sub(r"\s+", " ", (s or "").replace("\xa0", " ")).strip()


def to_iso(d):
    m = re.search(r"(\d{2})[-/](\d{2})[-/](\d{4})", d or "")
    return f"{m.group(3)}-{m.group(2)}-{m.group(1)}" if m else None


# ---------------------------------------------------------------------
# HTTP (robots.txt, retries, politeness)
# ---------------------------------------------------------------------
_session = requests.Session()
_session.headers.update({"User-Agent": UA, "Accept-Language": "fr-FR,fr;q=0.9"})
_robots = {}


def polite_get(url, check_robots=True, delay=(1.5, 3.0)):
    if check_robots and not is_allowed(url):
        print(f"  [skip] robots.txt disallows: {url}")
        return None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            r = _session.get(url, timeout=REQUEST_TIMEOUT)
            if r.status_code in (401, 403, 406, 429):
                print(f"  [blocked] HTTP {r.status_code}: {url}")
                if r.status_code in (403, 406):
                    print("     -> try --browser-ua, or run from a Tunisian connection")
                return None
            r.raise_for_status()
            return r
        except requests.RequestException as e:
            if attempt == MAX_RETRIES:
                print(f"  [error] giving up on {url}: {e}")
            else:
                w = 2.0 * 2 ** (attempt - 1)
                print(f"  [retry {attempt}/{MAX_RETRIES}] {e}; waiting {w:.0f}s")
                time.sleep(w)
        finally:
            time.sleep(random.uniform(*delay))
    return None


def is_allowed(url):
    if not RESPECT_ROBOTS:
        return True
    p = urlparse(url)
    if p.netloc not in _robots:
        rp = robotparser.RobotFileParser()
        r = polite_get(f"{p.scheme}://{p.netloc}/robots.txt", check_robots=False, delay=(0.5, 1.0))
        if r is None:
            rp.allow_all = True
        else:
            try:
                rp.parse(r.text.splitlines())
            except Exception:
                rp.allow_all = True
        _robots[p.netloc] = rp
    return _robots[p.netloc].can_fetch(_session.headers["User-Agent"], url)


# ---------------------------------------------------------------------
# IT RELEVANCE: keyword score + segment / OliveSoft fit
# ---------------------------------------------------------------------
IT_STRONG = [
    "informatique", "logiciel", "progiciel", "erp", "crm", "gpao", "ged", "cybersecurite",
    "securite informatique", "securite de l'information", "securite des systemes d'information",
    "systeme d'information", "systemes d'information", "systeme informatique",
    "systeme d'information geographique", "cloud", "data center", "datacenter", "hebergement",
    "site web", "portail web", "application mobile", "application web", "plateforme numerique",
    "plateforme digitale", "transformation digitale", "transformation numerique", "digitalisation",
    "numerisation", "dematerialisation", "intelligence artificielle", "machine learning", "big data",
    "base de donnees", "bases de donnees", "tma", "maintenance applicative", "infogerance",
    "licence logiciel", "antivirus", "firewall", "pare-feu", "vpn", "active directory", "ordinateur",
    "micro-ordinateur", "materiel informatique", "equipement informatique", "equipements informatiques",
    "reseau informatique", "reseau local", "cablage informatique", "cablage reseau",
    "telecommunication", "telecom", "wifi", "visioconference", "developpement logiciel",
    "developpement d'applications", "developpement d'une application", "developpement informatique",
    "audit informatique", "audit de securite", "audit de la securite", "sauvegarde", "stockage",
    "switch", "commutateur", "routeur", "serveur", "soc", "waf", "windows server", "sql server",
    "business intelligence", "vlan", "mpls", "fibre optique", "standard telephonique",
    "geolocalisation", "controle d'acces",
]
IT_WEAK = [
    "reseau", "application", "numerique", "digital", "digitale", "internet", "web", "donnees",
    "onduleur", "imprimante", "videosurveillance", "video surveillance", "camera", "telephonie",
    "supervision", "integration", "plateforme", "scanner", "tablette", "ecran", "developpement",
    "monitoring", "licence", "maintenance evolutive", "consommables informatiques", "cartouche",
    "toner", "gnss",
]
IT_EXCLUDE = [   # false friends, deleted before scoring
    "reseau d'eau", "reseaux d'eau", "reseau d'eaux", "reseau d'assainissement", "reseau routier",
    "reseau electrique", "reseau de distribution", "reseau ferroviaire", "reseau d'irrigation",
    "reseau de gaz", "reseau de transport", "reseau de canalisations", "developpement agricole",
    "developpement regional", "developpement durable", "developpement rural", "developpement local",
    "developpement des exportations", "developpement sylvo", "application de peinture",
    "application d'un enduit", "application de la loi", "applications thermiques", "plateforme de forage",
    "plateforme petroliere", "plateforme de loisir", "stockage d'energie", "batteries", "banquettes",
    "unite d'hebergement", "ancien hebergement",
]


def _term_re(t):
    return re.compile(r"(?<![a-z0-9])" + re.escape(t) + r"s?(?![a-z0-9])")


def _dedupe(terms):
    base = set(terms)
    return [t for t in dict.fromkeys(terms) if not (t.endswith("s") and t[:-1] in base)]


_STRONG = [(t, _term_re(t)) for t in _dedupe(IT_STRONG)]
_STRONG_SET = {t for t, _ in _STRONG}
_WEAK = [(t, _term_re(t)) for t in _dedupe(IT_WEAK) if t not in _STRONG_SET]


def it_score(text, extra_keywords=None):
    """(score, matched_terms): strong = 2 pts, weak = 1 pt, user keyword = 2 pts."""
    t = strip_accents(ARABIC_RE.sub(" ", text or ""))
    for ph in IT_EXCLUDE:
        t = t.replace(ph, " ")
    score, hits = 0, []
    for term, rx in _STRONG:
        if rx.search(t):
            score += 2
            hits.append(term)
    for term, rx in _WEAK:
        if rx.search(t):
            score += 1
            hits.append(term)
    for kw in (extra_keywords or []):
        kw = strip_accents(kw).strip()
        if kw and _term_re(kw).search(t):
            score += 2
            hits.append(kw)
    return score, sorted(set(hits))


SKILLS = [
    "python", "java", "javascript", "typescript", "react", "angular", "vue.js", "node.js", "django", "flask",
    "spring", "laravel", "php", ".net", "sql", "mysql", "postgresql", "oracle", "mongodb", "docker",
    "kubernetes", "aws", "azure", "gcp", "jenkins", "gitlab", "github", "rest api", "graphql", "linux",
    "windows server", "devops", "microservices", "ci/cd", "sap", "erp", "crm", "sharepoint", "power bi",
    "microsoft 365", "fortigate", "cisco", "vmware", "machine learning", "intelligence artificielle",
    "llm", "n8n", "langchain",
]
_SKILL_RX = [(s, re.compile(r"(?<![a-z0-9])" + re.escape(s) + r"(?![a-z0-9])")) for s in SKILLS]


def extract_skills(text):
    t = strip_accents(text or "")
    return sorted({s for s, rx in _SKILL_RX if rx.search(t)})


FIT_RANK = {"none": 0, "low": 1, "medium": 2, "high": 3}
FIT_BY_SEGMENT = {
    "ai_data": "high", "software_dev": "high", "cybersecurity": "medium", "cloud_infra": "medium",
    "network_telecom": "low", "licences_software": "low", "hardware_supply": "low", "it_other": "low",
    "physical_security_iot": "none", "consumables": "none", "digital_marketing": "none", "other": "none",
}
SEGMENT_LABEL = {
    "ai_data": "IA / data / BI", "software_dev": "Developpement logiciel / applications / ERP",
    "cybersecurity": "Cybersecurite", "cloud_infra": "Cloud / serveurs / infrastructure",
    "network_telecom": "Reseau / telecom", "licences_software": "Licences / logiciels sur etagere",
    "hardware_supply": "Fourniture de materiel informatique", "it_other": "Informatique (generique)",
    "physical_security_iot": "Videosurveillance / IoT / geoloc", "consumables": "Consommables / fournitures",
    "digital_marketing": "Communication digitale", "other": "Hors perimetre IT",
}
_SEG_RULES = [(name, [re.compile(p) for p in pats]) for name, pats in [
    ("ai_data", [r"intelligence artificielle", r"machine learning", r"apprentissage automatique", r"big data",
                 r"business intelligence", r"data ?warehouse", r"entrepot de donnees", r"\bchatbot", r"\bllm\b"]),
    ("cybersecurity", [r"securite (?:de l'information|informatique|reseau|des (?:systemes|donnees|reseaux))",
                       r"audit (?:de la |de )?securite", r"cybersecurite", r"\bsoc\b", r"security operations",
                       r"\bwaf\b", r"firewall", r"pare-feu", r"fortigate|fortinet", r"reseau et securite",
                       r"tests? d'intrusion|pentest"]),
    ("software_dev", [r"\bdeveloppement (?:d'|de |du |des |logiciel|informatique|web|mobile|sur mesure)",
                      r"solutions? logicielles?", r"\brefonte\b", r"\bprogiciels?\b", r"\berp\b", r"\bcrm\b",
                      r"\bgpao\b", r"\bged\b", r"\bapplications?\b", r"\bportails?\b", r"\bsites? web\b",
                      r"\bplateformes? (?:web|numerique|digitale|multicanaux?|informatique|de (?:gestion|dematerialisation))",
                      r"dematerialisation", r"digitalisation", r"transformation (?:digitale|numerique)"]),
    ("cloud_infra", [r"\bcloud\b", r"data ?center", r"\bserveurs?\b", r"virtualisation", r"\bvmware\b", r"\bazure\b",
                     r"\baws\b", r"windows server", r"sql server", r"microsoft (?:365|office 365|cloud)",
                     r"infrastructure (?:de production|de stockage|informatique|cloud|serveurs?)",
                     r"stockage (?:de donnees|informatique|reseau|san\b|nas\b)",
                     r"(?:infrastructure|baies?|solution) de stockage", r"sauvegarde (?:des |de |les )?donnees",
                     r"\bbackup\b",
                     r"hebergement (?:web|cloud|de sites?|d'applications?|de donnees|des donnees|des applications)"]),
    ("network_telecom", [r"reseaux? (?:informatique|local|lan|wifi|interne|sans fil)",
                         r"infrastructure (?:du |de )?reseaux?", r"\bcommutateurs?\b", r"\bswitch(?:es)?\b",
                         r"\brouteurs?\b", r"\bmpls\b", r"\bvpn\b", r"\bwi-?fi\b", r"cablage", r"fibre optique",
                         r"telecommunications?", r"telephonie", r"\binternet\b", r"\bsupervision\b",
                         r"\bmonitoring\b", r"\breseau\b"]),
    ("licences_software", [r"licen[cs]es?", r"\blogiciels?\b", r"antivirus"]),
    ("hardware_supply", [r"\bordinateurs?\b", r"micro-?ordinateurs?", r"\bpc\b",
                         r"\b(?:materiels?|equipements?)\b.{0,40}\binformatiques?\b", r"\bimprimantes?\b",
                         r"photocopieurs?", r"\bscanners?\b", r"\btablettes?\b", r"\bonduleurs?\b", r"\becrans?\b",
                         r"video ?projecteurs?", r"accessoires"]),
    ("it_other", [r"\binformatiques?\b"]),
    ("physical_security_iot", [r"video ?surveillance", r"\bcameras?\b", r"controle d'acces", r"geolocalisation",
                               r"\bgnss\b", r"\bscada\b"]),
    ("consumables", [r"consommables?", r"cartouches?", r"\bencre\b", r"\btoners?\b", r"fournitures? (?:de |d')?bureau"]),
    ("digital_marketing", [r"communication (?:digitale|numerique)", r"agence de communication"]),
]]


def classify(r, lots_txt):
    txt = " ".join([r.get("objet") or "", r.get("titre_portail_secondaire") or "", r.get("descriptif") or "", lots_txt])
    t = strip_accents(ARABIC_RE.sub(" ", txt))
    for ph in IT_EXCLUDE:
        t = t.replace(ph, " ")
    matched = [n for n, rxs in _SEG_RULES if any(rx.search(t) for rx in rxs)] or ["other"]
    if "consumables" in matched and set(matched) <= {"consumables", "it_other", "hardware_supply"}:
        matched = ["consumables"]                      # office supplies, not an IT project
    elif "consumables" in matched:
        matched.remove("consumables")
    primary = max(matched, key=lambda s: (FIT_RANK[FIT_BY_SEGMENT[s]], -matched.index(s)))
    return primary, matched, FIT_BY_SEGMENT[primary]


_BUYER_HINTS = [
    (r"universit|facult|ecole|institut superieur|enseignement", "Enseignement superieur / education"),
    (r"hopital|clinique|\bsante\b|medic", "Sante"),
    (r"commissariat", "Administration regionale (commissariat)"),
    (r"municipal|commune", "Collectivite locale"),
    (r"siege social|societe", "Entreprise / etablissement public"),
    (r"\bagence\b", "Agence publique"),
    (r"ministere", "Ministere"),
]


def buyer_hint(r):
    t = strip_accents(r.get("objet") or "")
    return next((label for pat, label in _BUYER_HINTS if re.search(pat, t)), None)


# ---------------------------------------------------------------------
# HAICOP: listing (JavaScript -> Playwright)
# ---------------------------------------------------------------------
_BLOCK_HINT = (
    "  -> Likely: the portal filters Colab's cloud IP. Run this file on YOUR computer (Tunisian connection):\n"
    "     pip install playwright && playwright install chromium && python cstam_pipeline.py\n"
    "     or pass tender ids copied from the browser:  --ids Tender-98007,Tender-100099\n"
    "     or use --demo to show the full pipeline on simulated tenders.")
_SEARCH_BUTTONS = ["button:has-text('Rechercher')", "input[value='Rechercher']", "a:has-text('Rechercher')",
                   "button[type='submit']"]
_NEXT_BUTTONS = ["a.paginate_button.next", ".dataTables_paginate .next", "li.next a", "a[rel='next']",
                 "a:has-text('Suivant')", "button:has-text('Suivant')", "a:has-text('Next')",
                 "a[aria-label*='uivant']", "a[aria-label*='ext']"]


def _harvest_ids(text, found, source=""):
    n0 = len(found)
    for tid in dict.fromkeys(TENDER_RE.findall(text or "")):
        found.setdefault(tid, {"tender_id": tid, "url": f"{BASE_HC}/fr/appels-doffres/{tid}"})
    if len(found) > n0:
        print(f"    + {len(found) - n0} tender id(s) from {source}")
    return len(found) - n0


def _listing_worker(max_pages, headless, debug_path):
    from playwright.sync_api import sync_playwright
    found, responses, done = {}, [], set()

    def harvest(page, tag):
        added = _harvest_ids(page.content(), found, f"{tag} / DOM")
        for r in responses:
            if id(r) in done:
                continue
            done.add(id(r))
            try:
                added += _harvest_ids(r.text(), found, f"{tag} / network {r.url[:70]}")
            except Exception:
                pass
        return added

    with sync_playwright() as pw:
        browser = pw.chromium.launch(headless=headless)
        ctx = browser.new_context(user_agent=BROWSER_UA, locale="fr-FR", viewport={"width": 1400, "height": 900})
        page = ctx.new_page()
        page.on("response", lambda r: responses.append(r) if (
            r.request.resource_type in ("xhr", "fetch") or "json" in r.headers.get("content-type", "")) else None)
        try:
            main = page.goto(LIST_URL, wait_until="networkidle", timeout=60000)
        except Exception as e:
            print(f"[haicop] could not load {LIST_URL}: {e}\n{_BLOCK_HINT}")
            browser.close()
            return []
        page.wait_for_timeout(2500)
        status = main.status if main else "?"
        body_txt = clean(page.inner_text("body"))
        print(f"[haicop] HTTP {status} | title={page.title()!r} | xhr/fetch seen={len(responses)}")
        if status not in (200, "?") or re.search(r"captcha|access denied|forbidden|cloudflare|blocked|robot",
                                                  body_txt[:1500], re.I):
            print(f"[haicop] page looks BLOCKED: {body_txt[:200]!r}\n{_BLOCK_HINT}")
        harvest(page, "initial load")

        if not found:                                   # results may need a click on 'Rechercher'
            for css in _SEARCH_BUTTONS:
                btn = page.query_selector(css)
                if btn and btn.is_visible():
                    try:
                        btn.click()
                        page.wait_for_load_state("networkidle", timeout=30000)
                    except Exception as e:
                        print(f"  [info] click/wait issue: {e}")
                    page.wait_for_timeout(2500)
                    if harvest(page, "after search"):
                        break
        if found:
            try:                                        # more rows per page
                sel = page.query_selector("select[name$='_length'], select[name*='length']")
                nums = [int(o.get_attribute("value")) for o in sel.query_selector_all("option")
                        if (o.get_attribute("value") or "").isdigit()] if sel else []
                if nums:
                    sel.select_option(str(max(nums)))
                    page.wait_for_load_state("networkidle")
                    page.wait_for_timeout(1500)
                    harvest(page, "page length")
            except Exception as e:
                print(f"  [info] page-length selector not usable: {e}")
            for page_no in range(2, max_pages + 1):
                nxt = next((page.query_selector(c) for c in _NEXT_BUTTONS if page.query_selector(c)), None)
                if not nxt:
                    break
                cls = (nxt.get_attribute("class") or "") + " " + (nxt.evaluate("e => e.parentElement.className") or "")
                if "disabled" in cls or nxt.get_attribute("aria-disabled") == "true":
                    break
                try:
                    nxt.click()
                    page.wait_for_load_state("networkidle", timeout=30000)
                except Exception:
                    pass
                page.wait_for_timeout(1500)
                print(f"[haicop] listing page {page_no}")
                if not harvest(page, f"page {page_no}"):
                    break
        if not found:
            with open(debug_path, "w", encoding="utf-8") as f:
                f.write(page.content())
            print(f"[haicop] NOTHING FOUND. Rendered page saved to {debug_path}")
        browser.close()
    return list(found.values())


def scrape_listing(max_pages, headless, debug_path):
    if not is_allowed(LIST_URL):
        print("[haicop] robots.txt disallows the listing page; stopping.")
        return []

    def go():
        with ThreadPoolExecutor(max_workers=1) as ex:    # avoids "sync API inside asyncio loop" in Colab
            return ex.submit(_listing_worker, max_pages, headless, debug_path).result()
    try:
        return go()
    except Exception as e:
        if "Executable doesn't exist" in str(e) or "playwright install" in str(e):
            print("[haicop] installing Chromium for Playwright (one-time)...")
            subprocess.run([sys.executable, "-m", "playwright", "install", "chromium"], check=False)
            subprocess.run([sys.executable, "-m", "playwright", "install-deps", "chromium"], check=False)
            try:
                return go()
            except Exception as e2:
                print(f"[haicop] listing failed after install: {e2}")
                return []
        print(f"[haicop] listing failed: {e}")
        return []


# ---------------------------------------------------------------------
# HAICOP: detail page -> fields, lots, documents
# ---------------------------------------------------------------------
LABELS = [
    "Objet", "Descriptif", "Date de publication", "Date de la dernière mise à jour", "Etat",
    "Numéro A.O", "Année", "Acheteur public", "Appel d'offre avec concours",
    "Procédure de passation", "Type de lots", "Nombre de lots", "Mode de financement",
    "Type de commande", "Caractère des prix", "Marché cadre", "Marché général",
    "Possibilité de groupement", "Délais de validité des offres", "Région d'exécution",
    "Date de début d'exécution", "Ancienne date de début d'exécution",
    "Lieu de retrait ou téléchargement des cahiers de charges",
    "Date de commencement de réception des offres", "Date limite de réception des offres",
    "Ancienne date limite de réception des offres", "Lieu de réception des offres",
    "Date d'ouverture des offres", "Ancienne date d'ouverture des offres",
    "Lieu d'ouverture des offres", "Méthodologie d'évaluation",
]
_LABEL_RE = re.compile(
    r"(?:(?<=\n)|(?<=^)|(?<=\s))(" + "|".join(re.escape(l) for l in sorted(LABELS, key=len, reverse=True))
    + r")(?=\s*[:\n\*]|\s+\S)")
_FOOTER_RX = re.compile(r"Avis du cosem|Si[eè]ge HAICOP", re.I)


def cut_footer(text):
    t = text or ""
    m = _FOOTER_RX.search(t)
    if m:
        t = t[:m.start()]
    t = re.sub(r"[ \t\xa0]+\n", "\n", t)
    return re.sub(r"\n{2,}", "\n", t).strip()


def parse_detail_text(page_text):
    text = (page_text or "").replace("\xa0", " ").replace("’", "'").replace("‘", "'").replace("*", "")
    text = re.sub(r"[ \t]+", " ", text)
    start = text.find("Détail de l'appel d'offres")
    if start != -1:
        text = text[start:]
    matches = []
    for m in _LABEL_RE.finditer(text):
        matches.append((m.group(1), m.start(), m.end()))
        if m.group(1) == "Méthodologie d'évaluation":
            break
    fields, lots_text = {}, ""
    for i, (label, s, e) in enumerate(matches):
        end = matches[i + 1][1] if i + 1 < len(matches) else len(text)
        value = text[e:end].strip(" :\n")
        if label == "Méthodologie d'évaluation":
            parts = value.split("\n", 1)
            fields[label] = clean(parts[0])
            lots_text = parts[1].strip() if len(parts) > 1 else ""
            continue
        fields.setdefault(label, clean(value))
    for dl in ["Date limite de réception des offres", "Date d'ouverture des offres"]:
        v = fields.get(dl, "")
        m = re.search(r"Heure\s*:?\s*(\d{1,2}:\d{2})", v)
        if m:
            fields[dl + " (heure)"] = m.group(1)
            fields[dl] = clean(v[:m.start()])
    v = fields.get("Délais de validité des offres", "")
    if v:
        nums = re.findall(r"\d+", v.replace("(en nombre de jours)", ""))
        fields["Délais de validité des offres"] = nums[-1] if nums else clean(v)
    return fields, cut_footer(lots_text)


def parse_lots(text):
    """'Lot 1 / Objet ... / Quantité / Région d'exécution / Cautionnement' -> list of dicts."""
    parts = re.split(r"(?m)^\s*Lot\s*(\d+)\s*$", cut_footer(text))
    lots = []
    for i in range(1, len(parts) - 1, 2):
        num, body = parts[i], parts[i + 1]
        m = re.search(r"Objet\s*(.*?)\s*(?=Quantit[eé]\s*:|R[eé]gion d.ex[eé]cution|Montant du cautionnement|\Z)", body, re.S)
        objet = re.sub(r"\s+", " ", m.group(1)).strip() if m else ""
        q = re.search(r"Quantit[eé]\s*:\s*(\d+)", body)
        reg = re.search(r"R[eé]gion d.ex[eé]cution\s*:?\s*([^\n]*)", body)
        region = reg.group(1).strip() if reg else ""
        if not region or region.lower().startswith("montant"):
            reg2 = re.search(r"R[eé]gion d.ex[eé]cution\s*:?\s*\n\s*([^\n]+)", body)
            region = reg2.group(1).strip() if reg2 else ""
        if region.lower().startswith(("montant", "quantit")):
            region = ""
        c = re.search(r"Montant du cautionnement provisoire\s*:?\s*(\d[\d\s.,]*)", body)
        lots.append({"lot": int(num), "objet": objet or None, "quantite": int(q.group(1)) if q else None,
                     "region": region or None,
                     "cautionnement_provisoire": re.sub(r"\s+", "", c.group(1)).rstrip(".,") if c else None})
    return lots


def parse_documents(soup):
    docs, seen = [], set()
    for a in soup.find_all("a", href=True):
        label = clean(a.get_text()).lower()
        href = a["href"].strip()
        if href.lower().startswith(("javascript", "#", "mailto")) or "cosem" in label:
            continue
        if any(k in label for k in ("cahier des charges", "avis d", "avis report", "autres")):
            url = urljoin(BASE_HC, href)
            if url not in seen:
                seen.add(url)
                docs.append({"label": clean(a.get_text()), "url": url})
    return docs


def _pdf_text(b):
    from pypdf import PdfReader
    try:
        return "\n".join((p.extract_text() or "") for p in PdfReader(io.BytesIO(b)).pages)
    except Exception as e:
        print(f"  [warn] unreadable PDF: {e}")
        return ""


def _docx_text(b):
    try:
        with zipfile.ZipFile(io.BytesIO(b)) as z:
            xml = z.read("word/document.xml").decode("utf-8", "ignore")
    except Exception:
        return ""
    xml = re.sub(r"<w:tab/>", " ", re.sub(r"</w:p>", "\n", xml))
    return html.unescape(re.sub(r"<[^>]+>", "", xml))


_warned_doc = False


def _doc_text(b):
    global _warned_doc
    exe = shutil.which("antiword") or shutil.which("catdoc")
    if not exe:
        if not _warned_doc:
            print("  [info] .doc notices skipped: run  !apt-get install -y antiword  to read them")
            _warned_doc = True
        return ""
    try:
        with tempfile.NamedTemporaryFile(suffix=".doc") as f:
            f.write(b)
            f.flush()
            out = subprocess.run([exe, f.name], capture_output=True, timeout=60).stdout
        try:
            return out.decode("utf-8")
        except UnicodeDecodeError:
            return out.decode("latin-1", "ignore")
    except Exception:
        return ""


def fetch_document_text(doc):
    """Public document read IN MEMORY (pdf / docx / doc); nothing is saved."""
    r = polite_get(doc["url"])
    if r is None or len(r.content) > MAX_DOC_BYTES:
        return ""
    b, ct = r.content, r.headers.get("content-type", "").lower()
    ext = doc["url"].lower().split("?")[0].rsplit(".", 1)[-1]
    if ext == "docx" or "wordprocessingml" in ct or (b[:2] == b"PK" and ext != "pdf"):
        return _docx_text(b)
    if ext == "doc" or "msword" in ct:
        return _doc_text(b)
    if "pdf" in ct or ext == "pdf" or b[:4] == b"%PDF":
        return _pdf_text(b)
    return ""


_SECTION_HEADERS = {
    "prescriptions": r"(cahier des prescriptions techniques|prescriptions techniques|consistance des prestations)",
    "personnel": r"(exigences en personnel|personnel (?:exig[eé]|minimum)|[eé]quipe (?:projet|technique|minimale))",
    "references": r"(r[eé]f[eé]rences (?:exig[eé]es|techniques)?|r[eé]f[eé]rences\b)",
    "criteres": r"(crit[eè]res d.[eé]valuation|crit[eè]res de s[eé]lection|crit[eè]res de notation)",
}


def extract_sections(doc_text, max_chars=1800):
    out = {}
    if not doc_text:
        return out
    hits = sorted((m.start(), m.end(), k) for k, pat in _SECTION_HEADERS.items()
                  for m in [re.search(pat, doc_text, re.I)] if m)
    for i, (s, e, key) in enumerate(hits):
        end = hits[i + 1][0] if i + 1 < len(hits) else len(doc_text)
        body = doc_text[e:end].strip(" :\n")[:max_chars].strip()
        if body:
            out[key] = body
    return out


def scrape_detail(row):
    resp = polite_get(row["url"])
    if resp is None:
        return None
    soup = BeautifulSoup(resp.text, "lxml")
    fields, lots_text = parse_detail_text(soup.get_text("\n"))
    if "Numéro A.O" not in fields:
        print(f"  [warn] no 'Numéro A.O' parsed for {row['tender_id']} (layout unexpected)")
        return None
    docs = parse_documents(soup)
    base = " ".join([fields.get("Objet", ""), fields.get("Descriptif", ""), lots_text])
    doc_text = ""
    # OPTIMISATION: only download documents when the page text already looks IT
    if docs and (it_score(base)[0] >= 1 or "informatique" in strip_accents(fields.get("Type de commande", ""))):
        for d in docs[:MAX_DOCS_PER_TENDER]:
            doc_text += "\n" + fetch_document_text(d)
    doc_text = doc_text.strip()
    score, hits = it_score(base + " " + doc_text[:5000] + " " + fields.get("Type de commande", ""))
    caution = re.findall(r"cautionnement provisoire\s*:?\s*([\d][\d\s.,]*)", lots_text, re.I)
    return {
        "source_site": "marchespublics.gov.tn (HAICOP)", "tender_id": row["tender_id"],
        "reference_raw": fields.get("Numéro A.O", ""), "year": fields.get("Année", ""),
        "acheteur": fields.get("Acheteur public", ""), "objet": fields.get("Objet", ""),
        "descriptif": fields.get("Descriptif", ""), "type_commande": fields.get("Type de commande", ""),
        "procedure": fields.get("Procédure de passation", ""), "financement": fields.get("Mode de financement", ""),
        "type_lots": fields.get("Type de lots", ""), "nombre_lots": fields.get("Nombre de lots", ""),
        "region": fields.get("Région d'exécution", ""), "groupement": fields.get("Possibilité de groupement", ""),
        "validite_offres_jours": fields.get("Délais de validité des offres", ""),
        "date_publication": to_iso(fields.get("Date de publication", "")),
        "date_maj": to_iso(fields.get("Date de la dernière mise à jour", "")),
        "date_debut_execution": to_iso(fields.get("Date de début d'exécution", "")),
        "date_debut_reception": to_iso(fields.get("Date de commencement de réception des offres", "")),
        "date_limite": to_iso(fields.get("Date limite de réception des offres", "")),
        "heure_limite": fields.get("Date limite de réception des offres (heure)", ""),
        "date_ouverture": to_iso(fields.get("Date d'ouverture des offres", "")),
        "heure_ouverture": fields.get("Date d'ouverture des offres (heure)", ""),
        "lieu_retrait_cdc": fields.get("Lieu de retrait ou téléchargement des cahiers de charges", ""),
        "lieu_reception": fields.get("Lieu de réception des offres", ""),
        "lieu_ouverture": fields.get("Lieu d'ouverture des offres", ""),
        "methodologie_evaluation": fields.get("Méthodologie d'évaluation", ""),
        "lots_text": lots_text, "cautionnements_provisoires": [clean(c).rstrip(".,") for c in caution],
        "documents": docs, "document_sections": extract_sections(doc_text),
        "doc_excerpt": doc_text[:4000] or None, "it_score": score, "it_terms": hits, "url": row["url"],
    }


def scrape_haicop(max_pages, max_tenders, it_only, min_score, extra_keywords, tender_ids, headless, debug_path):
    if tender_ids:
        rows = {}
        for x in tender_ids:
            m = TENDER_RE.search(x) or re.fullmatch(r"\s*(\d+)\s*", x)
            if m:
                tid = m.group(1) if m.group(1).startswith("Tender-") else f"Tender-{m.group(1)}"
                rows[tid] = {"tender_id": tid, "url": f"{BASE_HC}/fr/appels-doffres/{tid}"}
        rows = list(rows.values())
        print(f"[haicop] using {len(rows)} tender id(s) given manually")
    else:
        rows = scrape_listing(max_pages, headless, debug_path)
        print(f"[haicop] {len(rows)} tenders listed")
    out, skipped = [], 0
    for i, row in enumerate(rows[:max_tenders], 1):
        print(f"  [{i}/{min(len(rows), max_tenders)}] {row['tender_id']}")
        rec = scrape_detail(row)
        if rec is None:
            continue
        if extra_keywords:
            rec["it_score"], rec["it_terms"] = it_score(
                " ".join([rec["objet"], rec["descriptif"], rec["lots_text"], rec.get("doc_excerpt") or ""]), extra_keywords)
        keep = "informatique" in strip_accents(rec["type_commande"]) or rec["it_score"] >= min_score
        if it_only and not keep:
            skipped += 1
            continue
        out.append(rec)
    print(f"[haicop] kept {len(out)}, filtered out {skipped} (IT filter {'ON' if it_only else 'OFF'})")
    return out


# ---------------------------------------------------------------------
# appeloffres.com (public, server-rendered listing)
# ---------------------------------------------------------------------
DETAIL_RE = re.compile(r"^/appels-offres/([a-z0-9-]+)/(\d+)-([a-z0-9]+)/?$", re.I)
DATE_RE = re.compile(r"(\d{2})/(\d{2})/(\d{4})(?:\s+(\d{2}:\d{2})(?::\d{2})?)?")
TYPE_WORDS = ["National", "International", "Avis de report", "Avis d'infructuosité", "Avis de non attribution",
              "Avis de résultat"]


def _detail(href):
    path = urlparse(urljoin(BASE_AO, href)).path
    m = DETAIL_RE.match(path)
    return path, (m.group(2) if m else None)


def _country_from_row(cont):
    for img in cont.find_all("img"):
        src = (img.get("src") or "").lower()
        if "flag_" in src:
            label = clean(img.get("alt") or img.get("title") or "")
            if label:
                return label
            return {"tun": "Tunisie", "mar": "Maroc", "alg": "Algérie", "dza": "Algérie"}.get(
                re.search(r"flag_([a-z]+)", src).group(1), "")
    return ""


def parse_listing(page_html, slug):
    soup = BeautifulSoup(page_html, "lxml")
    anchors = {}
    for a in soup.find_all("a", href=True):
        path, tid = _detail(a["href"])
        if tid:
            anchors.setdefault(tid, []).append((a, path))
    rows = []
    for tid, lst in anchors.items():
        first_a, path = lst[0]
        cont = first_a
        while cont.parent is not None and cont.parent.name not in ("body", "html", "[document]"):
            ids = {_detail(x["href"])[1] for x in cont.parent.find_all("a", href=True)} - {None}
            if len(ids) > 1:
                break
            cont = cont.parent
        tokens = [clean(t) for t in cont.stripped_strings if clean(t)]
        flat = " ".join(tokens)
        cat_label = AO_CATEGORIES.get(slug, slug)
        for x in cont.find_all("a", href=True):
            if urlparse(urljoin(BASE_AO, x["href"])).path.rstrip("/") == f"/appels-offres/{slug}" and clean(x.get_text()):
                cat_label = clean(x.get_text())
                break
        code = clean(first_a.get_text())
        try:
            ci = tokens.index(cat_label)
        except ValueError:
            ci = next((i for i, t in enumerate(tokens) if cat_label in t), None)
        head = tokens[:ci] if ci is not None else tokens
        cand = [t for t in head if not t.isdigit() and t != code and t.lower() != "voir" and not DATE_RE.search(t)]
        title = cand[0] if cand else ""
        if ci is None and cand:
            title = max(cand, key=len)
        dates = list(DATE_RE.finditer(flat))
        pub = dl = None
        hour = ""
        if dates:
            d1 = dates[-1]
            dl = f"{d1.group(3)}-{d1.group(2)}-{d1.group(1)}"
            hour = d1.group(4) or ""
            if len(dates) >= 2:
                d0 = dates[0]
                pub = f"{d0.group(3)}-{d0.group(2)}-{d0.group(1)}"
        country = _country_from_row(cont)
        after = tokens[ci + 1:] if ci is not None else []
        ref_tokens, type_raw = [], ""
        for t in after:
            if DATE_RE.match(t) or t.lower() == "voir":
                break
            if t in TYPE_WORDS:
                type_raw = type_raw or t
            elif t != country:
                ref_tokens.append(t)
        reference = clean(" ".join(ref_tokens))
        rows.append({
            "tender_id": tid, "reference_raw": reference, "buyer_code": code if len(code) <= 3 else "",
            "objet": title, "titre_tronque": title.endswith("...") or title.endswith("…"),
            "type_commande": cat_label, "procedure": type_raw, "pays": country, "date_publication": pub,
            "date_limite": dl, "heure_limite": hour, "url": urljoin(BASE_AO, path), "source_site": "appeloffres.com"})
    return rows


def scrape_ao(max_pages, country, it_only, min_score, extra_keywords, debug_path):
    seen, kept, listed, d_country, d_it = set(), [], 0, 0, 0
    for slug in AO_CATEGORIES:
        n_pages = max_pages
        for page in range(1, max_pages + 1):
            url = f"{BASE_AO}/appels-offres/{slug}" + (f"?page={page}" if page > 1 else "")
            print(f"[appeloffres] {slug} page {page}/{n_pages}")
            r = polite_get(url, delay=(2.0, 3.5))
            if r is None:
                break
            if "/login" in r.url:
                print("[appeloffres] redirected to login: listing not public. Stopping.")
                break
            if page == 1:
                m = re.search(r"page\s*\d+\s*/\s*(\d+)", BeautifulSoup(r.text, "lxml").get_text(" "), re.I)
                if m:
                    n_pages = min(max_pages, int(m.group(1)))
            rows = parse_listing(r.text, slug)
            print(f"  parsed {len(rows)} tender rows")
            if not rows:
                with open(debug_path, "w", encoding="utf-8") as f:
                    f.write(r.text)
                print(f"  [debug] page saved to {debug_path}")
                break
            for rec in rows:
                listed += 1
                if rec["url"] in seen:
                    continue
                seen.add(rec["url"])
                if country != "all" and rec["pays"] and strip_accents(rec["pays"]) != strip_accents(country):
                    d_country += 1
                    continue
                rec["it_score"], rec["it_terms"] = it_score(rec["objet"], extra_keywords)
                if it_only and rec["it_score"] < min_score:
                    d_it += 1
                    continue
                kept.append(rec)
            if page >= n_pages:
                break
    print(f"[appeloffres] listed {listed} | other country: {d_country} | not IT: {d_it} | kept {len(kept)}")
    return kept


# ---------------------------------------------------------------------
# CLEANING / ENRICHMENT (edge cases + fields for RAG, agent, n8n, dashboard)
# ---------------------------------------------------------------------
KEY_FIELDS = ["numero_ao", "acheteur", "objet", "type_commande", "date_limite"]
_KIND_RX = re.compile(r"(?i)\b(avis de consul?tation|consul?tation|manifestation d.int[eé]r[eê]t|avis de report)\b")


def parse_reference(r):
    raw = re.sub(r"\s+", " ", str(r.get("reference_raw") or "")).strip()
    n, obj = strip_accents(raw), strip_accents(r.get("objet") or "")
    if "manifestation d'interet" in n:
        kind = "manifestation_interet"
    elif "avis de report" in n or strip_accents(r.get("procedure") or "") == "avis de report" or obj.startswith("report "):
        kind = "report"
    elif re.search(r"\bconsul?tation\b", n):
        kind = "consultation"
    else:
        kind = "appel_offres"
    ref = re.sub(r"\s+", " ", _KIND_RX.sub(" ", raw)).strip(" -:/.")
    ref = re.sub(r"(?i)^n[°o]?\s+(?=\S)", "", ref).strip()
    missing = not re.search(r"[A-Za-z0-9]", ref)
    return kind, (r.get("tender_id") if missing else ref), missing


def deadline_dt(r):
    try:
        y, m, d = (int(x) for x in str(r.get("date_limite")).split("-"))
    except Exception:
        return None, False
    mm = re.match(r"\s*(\d{1,2}):(\d{2})", str(r.get("heure_limite") or ""))
    hh, mi = (int(mm.group(1)), int(mm.group(2))) if mm else (0, 0)
    known = bool(mm) and (hh, mi) != (0, 0)            # "00:00" = time not published
    if not known:
        hh, mi = 23, 59
    try:
        return datetime(y, m, d, hh, mi, tzinfo=TUNIS), known
    except ValueError:
        return None, False


def _items(text):
    text = (text or "").strip()
    if not text:
        return []
    parts = re.split(r"\n\s*(?:\d+[.)]|[-•*])\s+", "\n" + text)
    return [p for p in (re.sub(r"\s+", " ", x).strip() for x in parts) if p]


def _sentences(text):
    """Split a descriptif into one requirement per sentence / bullet."""
    out = []
    for it in _items(text):
        out += [s.strip() for s in re.split(r"(?<=[.;])\s+(?=[A-Z\u00C0-\u00DE])", it) if s.strip()]
    return out


def _req_level(line):
    l = strip_accents(line)
    if re.search(r"souhait|un plus|optionnel|facultatif", l):
        return "souhaite"
    if re.search(r"exig|obligatoire|\bdoit\b|\bdoivent\b|imperatif|\brequis", l):
        return "exige"
    return "non_precise"


def extract_requirements(r, limit=25):
    """Requirement lines for the RAG / requirements matrix. Only source text, never invented."""
    srcs = _sentences(r.get("descriptif")) + [l["objet"] for l in (r.get("lots") or []) if l.get("objet")] \
        + _items((r.get("document_sections") or {}).get("prescriptions")) \
        + _items((r.get("document_sections") or {}).get("personnel"))
    out, seen = [], set()
    for s in srcs:
        s = re.sub(r"\s+", " ", ARABIC_RE.sub(" ", s)).strip()
        k = re.sub(r"\W+", " ", strip_accents(s))
        if len(s) >= 12 and k not in seen:
            seen.add(k)
            out.append({"text": s, "level": _req_level(s)})
    return out[:limit]


def completeness(r):
    s = 25 if r.get("acheteur") else 0
    s += 10 if r.get("objet") else 0
    s += 5 if (r.get("objet") and not r.get("titre_tronque")) else 0
    s += 20 if (r.get("descriptif") or r.get("lots") or r.get("doc_excerpt")) else 0
    s += 15 if r.get("date_limite") else 0
    s += 5 if r.get("deadline_time_known") else 0
    s += 10 if r.get("documents") else 0
    s += 10 if r.get("document_sections") else 0
    return s


def build_rag_query(r):
    lots = "; ".join(l["objet"] for l in (r.get("lots") or []) if l.get("objet") and not ARABIC_RE.search(l["objet"]))
    parts, seen = [], ""
    for p in (r.get("objet"), r.get("descriptif"), lots, (r.get("doc_excerpt") or "")[:1200]):
        p = re.sub(r"\s+", " ", p or "").strip()
        if p and p.lower() not in seen.lower():
            parts.append(p)
            seen += " " + p
    kw = ", ".join(dict.fromkeys(list(r.get("it_terms") or []) + list(r.get("skills_detected") or [])))
    q = f"{'. '.join(parts)} | Domaine: {SEGMENT_LABEL.get(r.get('segment'), '')} | Mots-cles: {kw}"
    return re.sub(r"\s+", " ", ARABIC_RE.sub(" ", q)).strip()


def lead_score(r):
    """0-100 ranking for the sales dashboard: fit + IT signal + urgency + data completeness."""
    if r["expired"]:
        return 0
    s = {"high": 60, "medium": 40, "low": 20, "none": 0}[r["olivesoft_fit"]]
    s += int(min(r.get("it_score") or 0, 10) * 1.5) + r["completeness"] // 10
    if r["urgent"]:
        s += 10
    elif r["days_left"] is not None and r["days_left"] <= 14:
        s += 5
    return min(s, 100)


def clean_row(r, now, prev):
    r = dict(r)
    flags = []
    r["documents"] = [d for d in (r.get("documents") or []) if "cosem" not in (d.get("label") or "").lower()]
    lots_txt = cut_footer(r.get("lots_text") or "")
    r["lots_text"], r["lots"] = lots_txt or None, parse_lots(lots_txt)
    obj = r.get("objet") or ""
    if ARABIC_RE.search(obj):                           # Arabic-only title -> French descriptif as title
        r["objet_ar"] = obj
        fr = (r.get("descriptif") or "").strip()
        if fr and not ARABIC_RE.search(fr):
            r["objet"] = fr
        else:
            flags.append("title_arabic_only")
    kind, ref, ref_missing = parse_reference(r)
    r["notice_kind"], r["numero_ao"] = kind, ref
    is_ao = "appeloffres" in (r.get("source_site") or "")
    r["missing_fields"] = [k for k in KEY_FIELDS if not r.get(k)]
    if ref_missing:
        flags.append("reference_missing")
        if is_ao and "numero_ao" not in r["missing_fields"]:
            r["missing_fields"].append("numero_ao")
    dl, known = deadline_dt(r)
    r["deadline_time_known"], r["deadline_at"] = known, dl.isoformat() if dl else None
    r["expired"] = bool(dl and dl < now)
    r["days_left"] = (dl.date() - now.date()).days if dl else None
    r["urgent"] = bool(dl and not r["expired"] and r["days_left"] <= 7)
    if "it_score" not in r:
        r["it_score"], r["it_terms"] = it_score(" ".join([r.get("objet") or "", r.get("descriptif") or "", lots_txt]))
    if not r.get("skills_detected"):
        r["skills_detected"] = extract_skills(" ".join([r.get("objet") or "", r.get("descriptif") or "", lots_txt,
                                                        r.get("doc_excerpt") or ""]))
    r["segment"], r["segments"], r["olivesoft_fit"] = classify(r, lots_txt)
    r["fit_rank"] = FIT_RANK[r["olivesoft_fit"]]
    r["buyer_hint"] = None if r.get("acheteur") else buyer_hint(r)
    r["completeness"] = completeness(r)
    r["detail_level"] = "full" if r["completeness"] >= 60 else "listing_only"
    r["requirements"] = extract_requirements(r)
    if not r.get("acheteur"):
        flags.append("buyer_unknown")
    if r.get("titre_tronque"):
        flags.append("title_truncated")
    if not known:
        flags.append("deadline_time_unknown")
    if kind == "report":
        flags.append("postponement_notice")
    if not (r.get("descriptif") or r["lots"] or r.get("doc_excerpt") or r.get("document_sections")):
        flags.append("no_requirements_text")
    if r["expired"]:
        flags.append("expired")
    if not r.get("date_limite"):
        flags.append("deadline_missing")
    r["quality_flags"] = flags
    r["lead_score"] = lead_score(r)
    r["priority"] = "hot" if r["lead_score"] >= 70 else "warm" if r["lead_score"] >= 45 else "cold"
    r["rag_query"] = build_rag_query(r)
    r["is_new"] = r["url"] not in prev
    r["first_seen_at"] = prev.get(r["url"]) or now.isoformat()
    return r


# ---------------------------------------------------------------------
# CROSS-PORTAL LINKING: an appeloffres.com row that matches a HAICOP record is folded into it
# ---------------------------------------------------------------------
def _norm_title(s):
    s = strip_accents(ARABIC_RE.sub(" ", s or ""))
    s = re.sub(r"(\.\.\.|…)\s*$", "", s.strip())
    return " ".join(re.sub(r"[^a-z0-9 ]+", " ", s).split())


def _sim(a, b):
    a, b = _norm_title(a), _norm_title(b)
    if not a or not b:
        return 0.0
    n = min(len(a), len(b), 70)                         # titles are truncated: compare equal-length prefixes
    return SequenceMatcher(None, a[:n], b[:n]).ratio()


def link_portals(hc_rows, ao_rows, threshold=0.8):
    linked, rest = 0, []
    for a in ao_rows:
        best, bs = None, 0.0
        for h in hc_rows:
            if not a.get("date_limite") or h.get("date_limite") != a.get("date_limite"):
                continue
            s = max(_sim(a.get("objet"), h.get("objet")), _sim(a.get("objet"), h.get("descriptif")))
            if s > bs:
                best, bs = h, s
        if best is not None and bs >= threshold:
            best.setdefault("also_listed_on", []).append({"source": a.get("source_site"), "url": a.get("url"),
                                                          "match": round(bs, 2)})
            best["titre_portail_secondaire"] = a.get("objet")
            linked += 1
        else:
            rest.append(a)
    print(f"[link] {linked} appeloffres.com row(s) folded into a HAICOP record")
    return list(hc_rows) + rest


# ---------------------------------------------------------------------
# DEMO FEED (only with --demo): clearly labelled simulated tenders that exercise every edge case
# ---------------------------------------------------------------------
def demo_rows(now):
    d = lambda n: (now + timedelta(days=n)).strftime("%Y-%m-%d")
    base = {"source_site": "simulated (demo)", "simulated": True, "pays": "Tunisie", "type_commande": "Informatique",
            "procedure": "Appel d'offres ouvert", "heure_limite": "10:00"}
    return [
        dict(base, tender_id="Demo-001", reference_raw="12/2026", url="demo://Demo-001",
             acheteur="Universite de Sousse", date_limite=d(5),
             objet="Refonte de la plateforme web de gestion des stages avec module d'intelligence artificielle",
             descriptif="Developpement d'une application web (React, Python, PostgreSQL) avec chatbot LLM. "
                        "Hebergement cloud exige. Experience de 3 projets similaires souhaitee."),
        dict(base, tender_id="Demo-002", reference_raw="Consultation N 45/2026", url="demo://Demo-002",
             acheteur="", date_limite=d(12), heure_limite="00:00",
             objet="Audit de securite du systeme d'information et tests d'intrusion",
             descriptif="Audit de securite informatique, revue des firewall et du reseau interne."),
        dict(base, tender_id="Demo-003", reference_raw="...", url="demo://Demo-003", acheteur="Municipalite de Sfax",
             date_limite=d(20), objet="طلب عروض لتطوير تطبيق",
             descriptif="Developpement d'une application mobile de services aux citoyens (Node.js, Docker)."),
        dict(base, tender_id="Demo-004", reference_raw="7/2026", url="demo://Demo-004", acheteur="Hopital Charles Nicolle",
             date_limite=d(-3), objet="Fourniture de serveurs et solution de sauvegarde des donnees...",
             titre_tronque=True, descriptif="Fourniture de serveurs Windows Server et VMware."),
        dict(base, tender_id="Demo-005", reference_raw="3/2026", url="demo://Demo-005", acheteur="Commune de Tunis",
             date_limite=d(9), objet="Fourniture de cartouches d'encre et de toners pour imprimantes",
             descriptif=""),
    ]


# ---------------------------------------------------------------------
# FILTER / FRAME / EXPORT
# ---------------------------------------------------------------------
COLUMNS = [
    "numero_ao", "tender_id", "notice_kind", "year", "acheteur", "buyer_hint", "objet", "objet_ar", "descriptif",
    "type_commande", "segment", "segments", "olivesoft_fit", "fit_rank", "lead_score", "priority", "it_score",
    "it_terms", "skills_detected", "requirements", "procedure", "financement", "type_lots", "nombre_lots", "lots",
    "region", "groupement", "validite_offres_jours", "date_publication", "date_maj", "date_debut_execution",
    "date_debut_reception", "date_limite", "heure_limite", "deadline_at", "deadline_time_known", "days_left",
    "urgent", "expired", "date_ouverture", "heure_ouverture", "lieu_retrait_cdc", "lieu_reception", "lieu_ouverture",
    "methodologie_evaluation", "lots_text", "cautionnements_provisoires", "documents", "document_sections",
    "doc_excerpt", "completeness", "detail_level", "quality_flags", "missing_fields", "rag_query", "pays",
    "buyer_code", "titre_tronque", "reference_raw", "also_listed_on", "titre_portail_secondaire", "url",
    "source_site", "simulated", "is_new", "first_seen_at", "detected_at",
]


def filter_rows(rows, keep_expired, min_fit):
    kept, dropped = [], []
    for r in rows:
        if r["expired"] and not keep_expired:
            dropped.append((r, "expired"))
        elif r["fit_rank"] < FIT_RANK[min_fit]:
            dropped.append((r, f"fit<{min_fit}"))
        else:
            kept.append(r)
    return kept, dropped


def to_frame(rows):
    df = pd.DataFrame(rows) if rows else pd.DataFrame(columns=COLUMNS)
    for c in COLUMNS:
        if c not in df.columns:
            df[c] = None
    if rows:
        df["detected_at"] = datetime.now(timezone.utc).isoformat()
        df = df.drop_duplicates(subset=["url"])
        df = df.sort_values(["lead_score", "date_limite"], ascending=[False, True], na_position="last").reset_index(drop=True)
    return df[COLUMNS]


def _records(df):
    return [] if df.empty else json.loads(df.to_json(orient="records", force_ascii=False))


def export_json(df, path):
    recs = _records(df)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(recs, f, ensure_ascii=False, indent=2)
    print(f"Saved JSON: {path} ({len(recs)} tenders)")


def export_csv(df, path):
    d = df.copy()
    for c in d.columns:
        d[c] = d[c].apply(lambda x: json.dumps(x, ensure_ascii=False) if isinstance(x, (list, dict)) else x)
    d.to_csv(path, index=False, encoding="utf-8-sig")
    print(f"Saved CSV: {path} ({len(d)} tenders)")


_MONTHS_FR = ["janvier", "fevrier", "mars", "avril", "mai", "juin", "juillet", "aout", "septembre", "octobre",
              "novembre", "decembre"]


def _ascii(t):
    s = str(t if t is not None else "")
    s = (s.replace("«", '"').replace("»", '"').replace("“", '"').replace("”", '"').replace("–", "-")
          .replace("—", "-").replace("’", "'").replace("‘", "'").replace("…", "..."))
    s = unicodedata.normalize("NFKD", ARABIC_RE.sub(" ", s))
    s = "".join(c for c in s if not unicodedata.combining(c))
    return xml_escape(s.encode("ascii", errors="replace").decode("ascii"))


def _long_date(iso):
    try:
        y, m, d = iso.split("-")
        return f"{int(d)} {_MONTHS_FR[int(m) - 1]} {y}"
    except Exception:
        return ""


def _header_line(r):
    proc = re.sub(r"(?i)^appel d.offres?\s*", "", str(r.get("procedure") or "")).strip()
    base = {"consultation": "CONSULTATION", "manifestation_interet": "MANIFESTATION D'INTERET",
            "report": "AVIS DE REPORT"}.get(r.get("notice_kind"), "APPEL D'OFFRES")
    num, tid = r.get("numero_ao") or r.get("tender_id") or "", r.get("tender_id") or ""
    return f"{base}{(' ' + proc.upper()) if proc else ''} N {num}{f' (ID {tid})' if tid and str(num) != tid else ''}"


def export_pdf(df, path):
    """One PDF, one tender per page, in the layout of sample_rfp_fr.pdf. Empty sections are left out."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
    body = ParagraphStyle("b", fontName="Helvetica", fontSize=10.5, leading=14.4)
    recs, story = _records(df), []
    if not recs:
        story.append(Paragraph("Aucun appel d'offres collecte lors de cette execution.", body))
    for i, r in enumerate(recs):
        if i:
            story.append(PageBreak())
        story += [Paragraph(_ascii(_header_line(r)), body), Spacer(1, 14.4)]
        for label, value in [("Client:", r.get("acheteur") or r.get("buyer_hint") or "non communique"),
                             ("Secteur:", r.get("type_commande") or "non communique"),
                             ("Date limite de soumission:", _long_date(r.get("date_limite")) or "non communique"),
                             ("Budget previsionnel:", "non communique")]:
            story.append(Paragraph(f"{label} {_ascii(value)}", body))
        secs, presc, keys = r.get("document_sections") or {}, [], []

        def add(v):
            v = re.sub(r"\s+", " ", ARABIC_RE.sub(" ", v or "")).strip()
            if not v:
                return
            k = re.sub(r"\W+", " ", strip_accents(re.sub(r"(?i)\((exige|souhaite)\)", "", v))).strip()
            if k in keys:
                return
            lvl = _req_level(v)
            keys.append(k)
            presc.append(v + (" (Exige)" if lvl == "exige" else " (Souhaite)" if lvl == "souhaite" else "")
                         if not re.search(r"\((exige|souhaite)\)\s*$", strip_accents(v)) else v)

        add(r.get("objet"))
        for v in _sentences(r.get("descriptif")):
            add(v)
        for l in (r.get("lots") or []):
            add(f"Lot {l['lot']} : {l['objet']}" if l.get("objet") else f"Lot {l['lot']}")
            if l.get("region"):
                add(f"Lot {l['lot']} - Region d'execution : {l['region']}")
            if l.get("cautionnement_provisoire"):
                add(f"Lot {l['lot']} - Cautionnement provisoire : {l['cautionnement_provisoire']}")
        for v in _items(secs.get("prescriptions")):
            add(v)
        if presc:
            story += [Spacer(1, 14.4), Paragraph("CAHIER DES PRESCRIPTIONS TECHNIQUES", body), Spacer(1, 14.4)]
            story += [Paragraph(f"{n}. {_ascii(v)}", body) for n, v in enumerate(presc, 1)]
        if secs.get("personnel"):
            story += [Spacer(1, 14.4), Paragraph("EXIGENCES EN PERSONNEL", body), Spacer(1, 14.4)]
            story += [Paragraph(f"- {_ascii(v)}", body) for v in _items(secs["personnel"])]
        if secs.get("references"):
            story += [Spacer(1, 14.4), Paragraph("REFERENCES", body), Spacer(1, 14.4),
                      Paragraph(_ascii(re.sub(r"\s+", " ", secs["references"]).strip()), body)]
        crit = secs.get("criteres") or r.get("methodologie_evaluation")
        if crit:
            story += [Spacer(1, 14.4), Paragraph("CRITERES D'EVALUATION", body), Spacer(1, 14.4)]
            story += [Paragraph(_ascii(re.sub(r"\s+", " ", v)), body)
                      for v in ([x.strip() for x in crit.splitlines() if x.strip()] if "\n" in crit else [crit])]
    SimpleDocTemplate(path, pagesize=A4, leftMargin=2.03 * cm, rightMargin=2.03 * cm, topMargin=2.03 * cm,
                      bottomMargin=2.03 * cm, title="Appels d'offres IT", author="OliveSoft RFP Intelligence").build(story)
    print(f"Saved PDF: {path} ({len(recs)} tenders)")


def quality_report(df, dropped, status, path):
    def count(col):
        return {str(k): int(v) for k, v in df[col].value_counts(dropna=False).items()} if len(df) else {}

    def tally(col):
        out = {}
        for lst in (df[col] if len(df) else []):
            for k in (lst or []):
                out[k] = out.get(k, 0) + 1
        return out
    rep = {"generated_at": datetime.now(TUNIS).isoformat(), "sources": status, "kept": int(len(df)),
           "by_source": count("source_site"), "by_fit": count("olivesoft_fit"), "by_priority": count("priority"),
           "by_segment": count("segment"), "by_detail_level": count("detail_level"),
           "by_notice_kind": count("notice_kind"), "urgent_leads": int(df["urgent"].sum()) if len(df) else 0,
           "missing_fields": tally("missing_fields"), "quality_flags": tally("quality_flags"),
           "dropped": [{"tender_id": r.get("tender_id"), "objet": (r.get("objet") or "")[:120], "reason": why,
                        "segment": r.get("segment")} for r, why in dropped]}
    with open(path, "w", encoding="utf-8") as f:
        json.dump(rep, f, ensure_ascii=False, indent=2)
    print(f"Saved quality report: {path}")
    return rep


def push_webhook(url, records):
    """Send the NEW, medium+ leads to an n8n Webhook node (POST, JSON body {'leads': [...]})."""
    leads = [r for r in records if r.get("is_new") and r.get("fit_rank", 0) >= 2]
    if not leads:
        print("[webhook] no new medium/high lead to send")
        return
    try:
        resp = requests.post(url, json={"count": len(leads), "leads": leads}, timeout=30)
        print(f"[webhook] sent {len(leads)} lead(s) -> HTTP {resp.status_code}")
    except requests.RequestException as e:
        print(f"[webhook] failed (outputs are already saved): {e}")


def _prev_urls(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return {r.get("url"): r.get("first_seen_at") for r in json.load(f) if isinstance(r, dict)}
    except (OSError, json.JSONDecodeError, TypeError):
        return {}


# ---------------------------------------------------------------------
# PIPELINE
# ---------------------------------------------------------------------
def run(a):
    os.makedirs(a.out_dir, exist_ok=True)
    P = {k: os.path.join(a.out_dir, f"{a.prefix}_{v}") for k, v in
         dict(json="combined.json", csv="combined.csv", pdf="report.pdf", qual="quality_report.json").items()}
    debug_path = os.path.join(a.out_dir, "listing_debug.html")
    prev, now, status = _prev_urls(P["json"]), datetime.now(TUNIS), {}
    kw = [k for k in a.keywords.split(",") if k.strip()]
    it_only, hc_rows, ao_rows = not a.all, [], []
    sources = [s.strip() for s in a.sources.split(",") if s.strip()]

    if a.demo:
        hc_rows = demo_rows(now)
        status["demo"] = f"{len(hc_rows)} simulated tenders"
    else:
        if "haicop" in sources:
            try:
                hc_rows = scrape_haicop(
                    a.hc_pages, a.max_tenders, it_only and not a.enrich,
                    a.min_score if a.min_score is not None else HC_MIN_SCORE, kw,
                    [x for x in re.split(r"[,\s]+", a.ids) if x], not a.headed, debug_path)
                status["haicop"] = f"{len(hc_rows)} tenders"
            except Exception as e:
                status["haicop"] = f"FAILED: {e}"
                traceback.print_exc()
        if "appeloffres" in sources:
            try:
                if a.browser_ua:
                    _session.headers["User-Agent"] = BROWSER_UA
                ao_rows = scrape_ao(a.pages, a.country.lower(), it_only,
                                    a.min_score if a.min_score is not None else AO_MIN_SCORE, kw, debug_path)
                status["appeloffres"] = f"{len(ao_rows)} tenders"
            except Exception as e:
                status["appeloffres"] = f"FAILED: {e}"
                traceback.print_exc()
    print("\n[sources]", status)

    cleaned = [clean_row(r, now, prev) for r in link_portals(hc_rows, ao_rows)]
    kept, dropped = filter_rows(cleaned, a.keep_expired, a.min_fit if it_only else "none")
    print(f"[filter] {len(kept)} kept | dropped {len(dropped)} "
          f"({sum(w == 'expired' for _, w in dropped)} expired, {sum(w != 'expired' for _, w in dropped)} below fit '{a.min_fit}')")
    for r, why in dropped[:40]:
        print(f"   - [{why}] {r.get('tender_id')} | {(r.get('objet') or '')[:90]}")

    df = to_frame(kept)
    if df.empty:
        print("[run] Nothing collected. NO mock data is used (use --demo for a labelled simulated feed). See the log above.")
    export_json(df, P["json"])                          # JSON first: the RAG must always find a valid file
    export_csv(df, P["csv"])
    try:
        export_pdf(df, P["pdf"])
    except Exception as e:
        print(f"  [warn] PDF export failed (JSON/CSV already written): {e}")
    rep = quality_report(df, dropped, status, P["qual"])
    print("[summary] fit:", rep["by_fit"], "| priority:", rep["by_priority"], "| urgent:", rep["urgent_leads"])
    if len(df):
        print(df[["lead_score", "priority", "numero_ao", "acheteur", "objet", "date_limite", "days_left"]]
              .head(10).to_string(index=False, max_colwidth=45))
    if a.webhook:
        push_webhook(a.webhook, _records(df))
    return df


def build_parser():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sources", default="haicop,appeloffres")
    ap.add_argument("--pages", type=int, default=5, help="appeloffres.com pages per category")
    ap.add_argument("--hc-pages", type=int, default=8, help="HAICOP listing pages")
    ap.add_argument("--max-tenders", type=int, default=80, help="HAICOP detail pages per run")
    ap.add_argument("--all", action="store_true", help="disable every IT / relevance filter")
    ap.add_argument("--min-score", type=int, default=None, help="default: 2 HAICOP, 1 appeloffres")
    ap.add_argument("--min-fit", default="low", choices=list(FIT_RANK), help="OliveSoft relevance gate")
    ap.add_argument("--enrich", action="store_true", help="scrape HAICOP unfiltered so appeloffres rows can be linked to it")
    ap.add_argument("--keywords", default="", help="extra IT keywords, comma separated")
    ap.add_argument("--country", default="tunisie", help="'tunisie' or 'all'")
    ap.add_argument("--ids", default="", help="HAICOP: skip the listing, comma-separated Tender-xxxxx ids")
    ap.add_argument("--keep-expired", action="store_true")
    ap.add_argument("--demo", action="store_true", help="labelled simulated tenders (no network)")
    ap.add_argument("--webhook", default="", help="n8n Webhook URL to receive the new leads")
    ap.add_argument("--out-dir", default=_HERE)
    ap.add_argument("--prefix", default="offers")
    ap.add_argument("--browser-ua", action="store_true")
    ap.add_argument("--headed", action="store_true")
    return ap


if __name__ == "__main__":
    _argv = shlex.split(RUN_ARGS) if RUN_ARGS.strip() else sys.argv[1:]
    _args, _ = build_parser().parse_known_args(_argv)     # tolerant of Colab/Jupyter's extra argv
    run(_args)