services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: olivesoft
      POSTGRES_PASSWORD: olivesoft
      POSTGRES_DB: rfp_system
    ports:
      - "5433:5432"        # ← changé ici (5433 côté Windows, 5432 reste interne au conteneur)
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  pgdata:
  qdrant_data: