# -*- coding: utf-8 -*-
"""rfp_scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFB6gW2RW2305J5rX4aYGIUeLPTHq_BN
"""

!pip install requests beautifulsoup4 -q

!python olivesoft_rfp_scraper.py

"""
OliveSoft x CSTAM 3.0 - Phase 1: Lead & Tender Detection Engine
================================================================
v5 - Two fixes below were found and verified by live-testing v4 against
real marchespublics.gov.tn pages (not just re-reading the code):

1. TITLE FALLBACK: some tenders (e.g. Tender-96634) store a cryptic
   internal reference code in "Objet" ("tma systeme AMEN") while the
   actual human-readable description sits in "Descriptif"
   ("maintenance applicatives du Systeme d'information Amen Social du
   MAS"). v4 only ever read "Objet", so such tenders would still be
   correctly FLAGGED as relevant (the category-based score alone clears
   the threshold) but would export with an unreadable title. Fixed by
   falling back to "Descriptif" when "Objet" is missing or too short to
   be informative.

2. APOSTROPHE NORMALIZATION: the site's own templates are inconsistent -
   bold, top-level field labels for single-lot tenders (e.g. "Region
   d'execution" on Tender-96634) render with a typographic/curly
   apostrophe (U+2019, "d'execution"), while the same label rendered
   inside a "LotN" block on multi-lot tenders (e.g. Tender-103899) uses a
   plain ASCII apostrophe. A label constant hardcoded with only one of
   the two would silently return "" for the other style. Fixed by
   normalizing curly apostrophes to ASCII across the extracted page text
   before any label search runs (same spirit as the existing
   plate-forme/plateforme normalization below).

v4 - HAICOP is now the primary/default source; WebManagerCenter is kept
but OFF by default (see CONFIG["enable_haicop"] / ["enable_wmc"]).

Why HAICOP first: it's the only source with zero legal ambiguity (open
Tunisian government data, no ToS reproduction ban, no robots.txt block -
unlike appeloffres.com, which explicitly forbids reproducing anything on
its site, or TUNEPS, which disallows bots outright). It also carries an
official "Type de commande" category, which is a much more reliable
relevance signal than free-text keyword matching on a news site.

v4 also re-tunes the relevance keywords to OliveSoft's REAL expertise.
A look at olivesoft.fr's actual reference list (BNP Paribas, Bouygues
Telecom, Groupe BPCE, Total Energies, RTE, and several LVMH maisons)
shows a Data/BI/CRM/integration consultancy (Salesforce, Qlik/Talend,
MuleSoft, Power BI, BigQuery partner) - narrower than generic "custom
software development". Keywords now also catch BI/data-integration/CRM
tenders specifically, not just bare "informatique"/"logiciel".

v3 fixed two structural bugs found by inspecting a real run's output,
on top of v2's domain tuning for OliveSoft (IT services / custom
software engineering).

SOURCES:
1. HAICOP / marchespublics.gov.tn - Tunisia's official public-procurement
   portal. TUNEPS excluded (robots.txt disallow + prior 403s).
2. WebManagerCenter (webmanagercenter.com) - real Tunisian business-news
   outlet, covers private/parapublic tenders that never reach HAICOP.

KNOWN LIMITATIONS (unchanged from v4, documented rather than fixed since
they require a bigger structural change - see documentation.tex):
- Multi-lot tenders: budget/region are extracted from the FIRST lot only
  (re.search only returns the first match). A tender with several lots
  will under-report the total guarantee amount. Summing across all lots
  would require parsing the repeated "LotN" blocks individually rather
  than doing one whole-text label search - left as a follow-up, not done
  here to keep this patch focused and reviewable.

WHAT CHANGED IN v3 (found in a real detection_queue.jsonl):
- WMC classification was reading the WHOLE page (soup.find("article") or
  soup falls back to the entire HTML when the theme has no <article> tag),
  so it was scoring sidebar tag-clouds, "articles similaires" widgets and
  nav boilerplate instead of the actual story. That's why land-sale
  notices from "Al Buhaira de DEVELOPPEMENT et d'Investissement" (a real
  estate company - "Développement" is just part of its legal name) kept
  matching "développement", and why totally unrelated pieces (a bank
  board-seat notice, a car-inspection story) all picked up "data" /
  "système" / "réseau" from page furniture, not their own content. Fixed
  by extracting text ONLY from <p> tags, which is where WordPress themes
  put the actual article body - not nav, not tag lists.
- Some archive-listing thumbnails render as a bare <img> inside the <a>,
  so a.get_text() was empty and one run captured raw HTML markup as the
  "title" instead. Fixed by no longer trusting listing-page anchor text
  at all: the title is now read from the fetched article page itself
  (<h1>/<title>), which is far more robust.
- The keyword filter was flagging genuine NEWS ARTICLES (a Zuckerberg
  gadget story, an "AI and oil prices" opinion piece) as relevant, because
  they mention "intelligence artificielle" / "numérique" without being a
  tender at all. Added a separate "does this even look like a tender"
  check (appel d'offres / cahier des charges / date limite / soumission-
  naire...) that must ALSO pass - relevance is now (is_a_tender AND
  is_software_related), not just a keyword hit anywhere in the text.
- Over-generic single-word keywords ("développement", "système", "réseau",
  "data", "numérique", "digital", "plateforme" used alone) caused most of
  the false positives above. They're now required as part of a specific
  compound phrase ("développement web", "système d'information", "réseau
  informatique"...) rather than matching bare.
- Added a freshness filter: WMC's own search turned up real articles from
  2004-2017. Interesting for context, useless for "detect NEW leads", so
  anything older than `wmc_max_age_days` is still stored (for audit) but
  no longer pushed into detection_queue.jsonl.

USAGE IN GOOGLE COLAB:
    !pip install requests beautifulsoup4 -q
    !python olivesoft_rfp_scraper.py
"""

import re
import json
import time
import sqlite3
import hashlib
import logging
from dataclasses import dataclass, asdict
from datetime import datetime, timedelta
from typing import Optional, List, Tuple

import requests
from bs4 import BeautifulSoup

# ---------------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------------
FRENCH_MONTHS = {
    "janvier": 1, "février": 2, "fevrier": 2, "mars": 3, "avril": 4, "mai": 5,
    "juin": 6, "juillet": 7, "août": 8, "aout": 8, "septembre": 9,
    "octobre": 10, "novembre": 11, "décembre": 12, "decembre": 12,
}

CONFIG = {
    # Source toggles. HAICOP is the default/primary source (open government
    # data, no ToS issue). WMC is kept implemented but OFF by default -
    # flip to True once you want the secondary private/parapublic-tender
    # signal back; it needs more babysitting (see v3 notes above).
    "enable_haicop": True,
    "enable_wmc": False,

    "haicop_home": "https://www.marchespublics.gov.tn/fr",
    "haicop_tender_url_tpl": "https://www.marchespublics.gov.tn/fr/appels-doffres/Tender-{id}",
    "haicop_id_backfill": 60,

    "wmc_listing_url_tpl": "https://www.webmanagercenter.com/appels-doffres/page/{page}/",
    "wmc_pages_to_scan": 2,
    "wmc_search_url_tpl": "https://www.webmanagercenter.com/?s={query}",
    "wmc_search_keywords": [
        "appel d'offres informatique", "appel d'offres logiciel",
        "appel d'offres digital", "cahier des charges informatique",
    ],
    "wmc_max_age_days": 400,  # ~13 months - older hits are kept in the DB but not exported

    "request_timeout": 15,
    "request_delay_seconds": 1.5,
    "max_retries": 2,

    "db_path": "ctam_tenders.db",
    "jsonl_path": "detection_queue.jsonl",

    "user_agent": "OliveSoft-CTAM-RFP-Bot/1.0 (CSTAM 3.0 challenge; contact: set-your-email@olivesoft.example)",

    "haicop_software_category_hints": [
        "informatique", "logiciel", "développement", "digital", "numérique",
        "système d'information", "site web", "site internet", "application",
    ],
    # HAICOP doesn't have a category more specific than "Informatique", so
    # the category hint above still triggers the base score; this list adds
    # extra score when the TITLE also mentions something in OliveSoft's
    # actual expertise (Data/BI/CRM/integration), so those tenders rank
    # above a bare "acquisition d'ordinateurs" hardware purchase.
    "haicop_priority_expertise_hints": [
        "business intelligence", "intégration de données", "data warehouse",
        "entrepôt de données", "crm", "erp", "salesforce", "mulesoft",
        "power bi", "bigquery", "qlik", "talend", "tableau de bord",
        "reporting", "data platform", "gouvernance des données",
    ],
    "haicop_hardware_only_hints": [
        "consommables informatiques", "matériels informatiques",
        "matériel informatique", "toner", "imprimante", "photocopieur",
    ],

    # Phrases that indicate the text is genuinely a SPECIFIC tender/
    # procurement notice, not a news article or opinion piece that merely
    # discusses tenders/IT in general terms. Deliberately NOT including a
    # bare "appel d'offres" - too many op-eds about the tender system
    # itself ("les professionnels face aux appels d'offres infructueux")
    # contain that phrase without being an actual, actionable notice.
    "tender_signal_phrases": [
        "avis d'appel d'offres", "avis d’appel d’offres", "avis d'appel doffres",
        "lance un appel d'offres", "lance un appel d’offres",
        "lance une consultation", "appel d'offres national", "appel d’offres national",
        "appel d'offres international", "appel d’offres international",
        "cahier des charges", "manifestation d'intérêt", "manifestation d’intérêt",
        "soumissionnaire", "date limite de réception", "consultation restreinte",
        "recrutement d'un consultant", "avis de sollicitation",
    ],

    # Software-relevance phrases. A handful of unambiguous single words are
    # kept bare; everything else must appear as a specific compound phrase
    # so generic words (système, réseau, data, développement...) don't fire
    # on unrelated company names or page furniture.
    "software_keywords": [
        "informatique", "logiciel", "progiciel", "cybersécurité", "cloud",
        "saas", "api", "erp", "crm",
        "développement web", "développement logiciel", "développement mobile",
        "développement d'application", "développement d’application",
        "application web", "application mobile", "site internet",
        "plateforme", "plateforme numérique", "plateforme digitale",
        "système d'information",
        "système d’information", "système informatique", "réseau informatique",
        "base de données", "sécurité informatique", "intelligence artificielle",
        "transformation digitale", "transformation numérique", "digitalisation",
        "dématérialisation", "hébergement informatique",
        # Added for OliveSoft's actual Data/BI/CRM/integration positioning
        # (see olivesoft.fr references: BNP Paribas, Bouygues Telecom,
        # Groupe BPCE, Total Energies, RTE, several LVMH maisons).
        "business intelligence", "intégration de données", "data warehouse",
        "entrepôt de données", "salesforce", "mulesoft", "power bi",
        "bigquery", "qlik", "talend", "gouvernance des données",
        "tableau de bord décisionnel", "informatique décisionnelle",
    ],
    "export_relevance_threshold": 0.3,

    # Below this length, "Objet" is treated as an internal reference code
    # rather than a real description (verified live: Tender-96634's Objet
    # is "tma systeme AMEN" - 16 chars - while the real description lives
    # in "Descriptif"). Tune with care: too high and you'll discard
    # legitimately short-but-real titles.
    "min_title_length": 20,
}

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
log = logging.getLogger("ctam_scraper")

SESSION = requests.Session()
SESSION.headers.update({"User-Agent": CONFIG["user_agent"]})


@dataclass
class Tender:
    source: str
    external_id: str
    title: str
    organization: str = ""
    domain_type: str = ""
    published_date: str = ""
    deadline: str = ""
    budget: Optional[float] = None
    region: str = ""
    url: str = ""
    raw_excerpt: str = ""
    is_it_relevant: bool = False
    confidence_score: float = 0.0
    relevance_reasons: str = ""

    def dedup_hash(self) -> str:
        if self.source == "WebManagerCenter":
            # Free-text org extraction on WMC is a heuristic and can pull a
            # slightly different substring for two copies of the same
            # story (e.g. a republished/duplicate post), which would
            # otherwise defeat dedup. Title + publish date is a far more
            # stable identity for a news article than the org guess.
            date_key = self.published_date or re.search(r"/(\d{4}/\d{2}/\d{2})/", self.url).group(1) \
                if re.search(r"/(\d{4}/\d{2}/\d{2})/", self.url) else self.published_date
            key = f"{self.title.strip().lower()}|{self.source}|{date_key}"
        else:
            key = f"{self.title.strip().lower()}|{self.organization.strip().lower()}|{self.deadline}|{self.source}"
        return hashlib.md5(key.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Persistent storage (SQLite) + audit log
# ---------------------------------------------------------------------------
class TenderStore:
    def __init__(self, db_path: str):
        self.conn = sqlite3.connect(db_path)
        self._init_schema()

    def _init_schema(self):
        self.conn.execute("""
            CREATE TABLE IF NOT EXISTS tenders (
                hash TEXT PRIMARY KEY,
                source TEXT, external_id TEXT, title TEXT, organization TEXT,
                domain_type TEXT, published_date TEXT, deadline TEXT,
                budget REAL, region TEXT, url TEXT, is_it_relevant INTEGER,
                confidence_score REAL, relevance_reasons TEXT, status TEXT,
                first_seen TEXT, last_seen TEXT
            )
        """)
        self.conn.execute("""
            CREATE TABLE IF NOT EXISTS events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                tender_hash TEXT, event_type TEXT, timestamp TEXT
            )
        """)
        self.conn.commit()

    def upsert(self, t: Tender) -> bool:
        h = t.dedup_hash()
        now = datetime.utcnow().isoformat()
        is_new = self.conn.execute("SELECT 1 FROM tenders WHERE hash=?", (h,)).fetchone() is None
        if is_new:
            self.conn.execute(
                """INSERT INTO tenders (hash, source, external_id, title, organization,
                       domain_type, published_date, deadline, budget, region, url,
                       is_it_relevant, confidence_score, relevance_reasons, status,
                       first_seen, last_seen)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (h, t.source, t.external_id, t.title, t.organization, t.domain_type,
                 t.published_date, t.deadline, t.budget, t.region, t.url,
                 int(t.is_it_relevant), t.confidence_score, t.relevance_reasons,
                 "new", now, now),
            )
            self.conn.execute(
                "INSERT INTO events (tender_hash, event_type, timestamp) VALUES (?,?,?)",
                (h, "discovered", now),
            )
        else:
            self.conn.execute("UPDATE tenders SET last_seen=? WHERE hash=?", (now, h))
        self.conn.commit()
        return is_new

    def stats(self) -> dict:
        total, budget = self.conn.execute("SELECT COUNT(*), SUM(budget) FROM tenders").fetchone()
        it_relevant = self.conn.execute("SELECT COUNT(*) FROM tenders WHERE is_it_relevant=1").fetchone()[0]
        return {"total_tenders": total or 0, "total_budget_tnd": budget or 0.0, "it_relevant": it_relevant}

    def seen_external_id(self, source: str, external_id: str) -> bool:
        """Cheap pre-fetch check: a HAICOP Tender-<id> page's content never
        changes once published, so if we've already stored this exact
        (source, external_id) there is no point re-downloading and
        re-parsing it just to find out it's a duplicate. Skip the network
        call entirely instead."""
        row = self.conn.execute(
            "SELECT 1 FROM tenders WHERE source=? AND external_id=? LIMIT 1", (source, external_id)
        ).fetchone()
        return row is not None


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
def fetch(url: str) -> Optional[str]:
    for attempt in range(CONFIG["max_retries"] + 1):
        try:
            resp = SESSION.get(url, timeout=CONFIG["request_timeout"])
            time.sleep(CONFIG["request_delay_seconds"])
            if resp.status_code == 404:
                return None
            resp.raise_for_status()
            resp.encoding = resp.apparent_encoding
            return resp.text
        except requests.RequestException as e:
            log.warning(f"Attempt {attempt + 1} failed for {url}: {e}")
            time.sleep(2 * (attempt + 1))
    log.error(f"Giving up on {url}")
    return None


def _normalize_for_matching(text: str) -> str:
    """French sometimes hyphenates or spaces out a compound that our
    keyword list expects solid ('plate-forme'/'plate forme' for
    'plateforme') - a real HAICOP tender ("acquisition des licences pour
    le site de plateforme TUNEPS...") was missed in one run only because
    of this. Normalize the known variants before matching.

    Also normalizes typographic (curly) apostrophes to plain ASCII ones.
    Verified live on marchespublics.gov.tn: the same field label renders
    with a curly apostrophe (Région d'exécution, U+2019) in a single-lot
    tender's top-level template, but with a plain ASCII apostrophe when
    the same label appears inside a per-lot "LotN" block on a multi-lot
    tender. A label constant hardcoded with only one style would silently
    return "" on pages using the other."""
    text = text.replace("\u2019", "'").replace("\u2018", "'")
    return re.sub(r"plate[\s-]forme", "plateforme", text, flags=re.I)


def _keyword_hits(text: str, keywords: List[str]) -> List[str]:
    text_l = _normalize_for_matching(text).lower()
    hits = []
    for kw in keywords:
        pattern = r"\b" + re.escape(kw.lower()) + r"\w*"
        if re.search(pattern, text_l):
            hits.append(kw)
    return hits


def looks_like_tender(text: str) -> bool:
    return bool(_keyword_hits(text, CONFIG["tender_signal_phrases"]))


def classify_software_relevance(text: str) -> Tuple[bool, float, List[str]]:
    """A tender is only flagged relevant if it BOTH looks like an actual
    tender/procurement notice AND mentions something in OliveSoft's
    domain - mentioning 'intelligence artificielle' in a news op-ed is
    not a lead."""
    if not looks_like_tender(text):
        return False, 0.0, []
    hits = _keyword_hits(text, CONFIG["software_keywords"])
    score = round(min(1.0, 0.2 * len(hits)), 2)
    return bool(hits), score, hits


def classify_haicop_relevance(title: str, domain_type: str) -> Tuple[bool, float, List[str]]:
    dt_l = domain_type.lower()
    reasons = []
    score = 0.0

    is_hardware_only = any(h in dt_l for h in CONFIG["haicop_hardware_only_hints"])
    is_software_category = any(h in dt_l for h in CONFIG["haicop_software_category_hints"])

    if is_software_category and not is_hardware_only:
        score += 0.6
        reasons.append(f"category:{domain_type}")
    elif is_hardware_only:
        score += 0.1
        reasons.append(f"hardware-only-category:{domain_type}")

    title_hits = _keyword_hits(title, CONFIG["software_keywords"])
    if title_hits:
        score += min(0.4, 0.15 * len(title_hits))
        reasons.append("title:" + ",".join(title_hits))

    priority_hits = _keyword_hits(title, CONFIG["haicop_priority_expertise_hints"])
    if priority_hits:
        score += 0.2  # ranks BI/CRM/data-integration tenders above bare hardware buys
        reasons.append("olivesoft-expertise:" + ",".join(priority_hits))

    score = round(min(1.0, score), 2)
    return score >= CONFIG["export_relevance_threshold"], score, reasons


def extract_label_value(text: str, label: str) -> str:
    m = re.search(re.escape(label) + r"\s*:?\s*(.+)", text)
    if not m:
        return ""
    val = m.group(1).splitlines()[0].strip()[:300]
    if val.endswith(":") or val.lower().startswith(("date de", "numéro", "acheteur", "vous voulez")):
        return ""
    return val


def scope_to_detail_block(full_text: str) -> str:
    marker = "Numéro A.O"
    idx = full_text.find(marker)
    return full_text[idx:] if idx != -1 else full_text


def looks_like_date(value: str) -> bool:
    return bool(re.match(r"\d{2}-\d{2}-\d{4}", value))


def parse_amount(text: str) -> Optional[float]:
    m = re.search(r"[\d][\d\s]{2,}(?:[.,]\d+)?", text)
    if not m:
        return None
    try:
        return float(m.group(0).replace(" ", "").replace(",", "."))
    except ValueError:
        return None


def parse_french_date(text: str) -> Optional[datetime]:
    m = re.search(r"(\d{1,2})\s+(" + "|".join(FRENCH_MONTHS) + r")\s+(\d{4})", text.lower())
    if not m:
        return None
    day, month_name, year = m.groups()
    try:
        return datetime(int(year), FRENCH_MONTHS[month_name], int(day))
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# SOURCE 1: HAICOP / marchespublics.gov.tn
# ---------------------------------------------------------------------------
HAICOP_TENDER_LINK_RE = re.compile(r"/fr/appels-doffres/(Tender-(\d+))")


def haicop_discover_recent_ids() -> List[int]:
    html = fetch(CONFIG["haicop_home"])
    if not html:
        return []
    return sorted({int(m.group(2)) for m in HAICOP_TENDER_LINK_RE.finditer(html)}, reverse=True)


def haicop_resolve_title(full_text: str, tender_id: str) -> str:
    """Prefer "Objet" as the title, but fall back to "Descriptif" when
    "Objet" is missing or too short to be an informative title.

    Verified live: Tender-96634's "Objet" is the internal reference code
    "tma systeme AMEN" (16 chars), while its "Descriptif" is the real,
    actionable description ("maintenance applicatives du Systeme
    d'information Amen Social du MAS"). Falling back keeps the export
    usable for tenders that follow this pattern, without discarding
    "Objet" for the (more common) tenders where it's already descriptive
    (e.g. Tender-103899's Objet: "Acquisition de materiel roulant")."""
    objet = extract_label_value(full_text, "Objet")
    descriptif = extract_label_value(full_text, "Descriptif")
    if objet and len(objet) >= CONFIG["min_title_length"]:
        return objet
    if descriptif:
        return descriptif
    return objet or f"Tender {tender_id}"


def haicop_parse_tender(full_text: str, tender_id: str, url: str) -> Optional[Tender]:
    full_text = _normalize_for_matching(full_text)
    if "Numéro A.O" not in full_text:
        return None

    title = haicop_resolve_title(full_text, tender_id)
    text = scope_to_detail_block(full_text)
    org = extract_label_value(text, "Acheteur public")
    domain_type = extract_label_value(text, "Type de commande")
    region = extract_label_value(text, "Région d'exécution")

    deadline = extract_label_value(text, "Date limite de réception des offres")
    if not looks_like_date(deadline):
        deadline = ""
    published = extract_label_value(text, "Date de publication")
    if not looks_like_date(published):
        published = ""

    budget = parse_amount(extract_label_value(text, "Montant du cautionnement provisoire") or "")

    is_relevant, score, reasons = classify_haicop_relevance(title, domain_type)

    return Tender(
        source="HAICOP", external_id=tender_id, title=title or f"Tender {tender_id}",
        organization=org, domain_type=domain_type, published_date=published,
        deadline=deadline, budget=budget, region=region, url=url,
        raw_excerpt=text[:500], is_it_relevant=is_relevant, confidence_score=score,
        relevance_reasons="; ".join(reasons),
    )


def run_haicop_scraper(store: TenderStore) -> List[Tender]:
    log.info("HAICOP: discovering recent tender IDs from the homepage widget ...")
    recent_ids = haicop_discover_recent_ids()
    if not recent_ids:
        log.warning("HAICOP: no IDs discovered - site may be unreachable or its layout changed.")
        return []

    newest = max(recent_ids)
    window = range(newest, max(newest - CONFIG["haicop_id_backfill"], 0), -1)
    log.info(f"HAICOP: newest ID={newest}, scanning {CONFIG['haicop_id_backfill']} IDs backward")

    new_tenders = []
    skipped_known = 0
    for tid in window:
        ext_id = f"Tender-{tid}"
        if store.seen_external_id("HAICOP", ext_id):
            skipped_known += 1
            continue
        url = CONFIG["haicop_tender_url_tpl"].format(id=tid)
        html = fetch(url)
        if not html:
            continue
        text = BeautifulSoup(html, "html.parser").get_text("\n")
        tender = haicop_parse_tender(text, ext_id, url)
        if tender and store.upsert(tender):
            new_tenders.append(tender)
            flag = "IT-relevant" if tender.is_it_relevant else "other"
            log.info(f"  + new [{ext_id}] ({flag}, score={tender.confidence_score}) {tender.title[:60]}")
    if skipped_known:
        log.info(f"HAICOP: skipped {skipped_known} already-known IDs without a network call")
    return new_tenders


# ---------------------------------------------------------------------------
# SOURCE 2: WebManagerCenter - generic archive + targeted domain searches
# ---------------------------------------------------------------------------
WMC_ARTICLE_RE = re.compile(r"https://www\.webmanagercenter\.com/\d{4}/\d{2}/\d{2}/[^\s\"'<>]+")


def wmc_discover_links() -> List[str]:
    urls = []
    seen = set()

    for page in range(1, CONFIG["wmc_pages_to_scan"] + 1):
        html = fetch(CONFIG["wmc_listing_url_tpl"].format(page=page))
        if not html:
            break
        found = set(WMC_ARTICLE_RE.findall(html))
        if not found:
            break
        for href in found:
            if href not in seen:
                seen.add(href)
                urls.append(href)

    for kw in CONFIG["wmc_search_keywords"]:
        query = kw.replace("'", "%27").replace(" ", "+")
        html = fetch(CONFIG["wmc_search_url_tpl"].format(query=query))
        if not html:
            continue
        for href in set(WMC_ARTICLE_RE.findall(html)):
            if href not in seen:
                seen.add(href)
                urls.append(href)

    return urls


def _clean_wp_title(raw: str) -> str:
    # WordPress <title> tags are usually "Article Title - Site Name"
    return re.split(r"\s*[-–]\s*WebManagerCenter", raw, flags=re.I)[0].strip()


def wmc_parse_article(html: str, url: str) -> Optional[Tender]:
    soup = BeautifulSoup(html, "html.parser")

    h1 = soup.find("h1")
    if h1 and h1.get_text(strip=True):
        title = h1.get_text(strip=True)
    elif soup.title and soup.title.string:
        title = _clean_wp_title(soup.title.string)
    else:
        title = url.rstrip("/").split("/")[-1].replace("-", " ").capitalize()

    # Real article body: WordPress themes put story text in <p> tags; nav,
    # tag clouds and "related articles" widgets are lists/links, not prose.
    paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]
    body_text = "\n".join(p for p in paragraphs if len(p) > 25)
    if not body_text:
        return None

    org_match = re.search(r"(?:[Ll]a société|[Ll]e|[Ll]a|[Ll]'|[Ll]’)\s+([A-ZÉÈÀ][\w'’\- ]{2,60})", body_text)
    organization = org_match.group(0).strip() if org_match else ""

    is_relevant, score, hits = classify_software_relevance(f"{title}\n{body_text}")
    pub_dt = parse_french_date(body_text[:200]) or parse_french_date(title)

    return Tender(
        source="WebManagerCenter", external_id=url.rstrip("/").split("/")[-1],
        title=title, organization=organization, domain_type="Annonce presse",
        published_date=pub_dt.strftime("%d-%m-%Y") if pub_dt else "",
        deadline="", budget=None, region="",
        url=url, raw_excerpt=body_text[:500], is_it_relevant=is_relevant,
        confidence_score=score, relevance_reasons=",".join(hits),
    ), pub_dt


def run_wmc_scraper(store: TenderStore) -> List[Tender]:
    log.info("WebManagerCenter: scanning archive + running OliveSoft keyword searches ...")
    urls = wmc_discover_links()
    if not urls:
        log.warning("WebManagerCenter: no links discovered - site may be unreachable or its layout changed.")
        return []

    cutoff = datetime.utcnow() - timedelta(days=CONFIG["wmc_max_age_days"])
    new_tenders = []
    for href in urls:
        html = fetch(href)
        if not html:
            continue
        parsed = wmc_parse_article(html, href)
        if not parsed:
            continue
        tender, pub_dt = parsed
        is_new = store.upsert(tender)
        if not is_new:
            continue
        if pub_dt and pub_dt < cutoff:
            log.info(f"  (stored, too old to export: {pub_dt.date()}) {tender.title[:60]}")
            continue
        new_tenders.append(tender)
        flag = "IT-relevant" if tender.is_it_relevant else "other"
        log.info(f"  + new ({flag}, score={tender.confidence_score}) {tender.title[:60]}")
    return new_tenders


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------
def export_jsonl(tenders: List[Tender], path: str) -> int:
    relevant = [t for t in tenders if t.is_it_relevant]
    if not relevant:
        return 0
    with open(path, "a", encoding="utf-8") as f:
        for t in relevant:
            f.write(json.dumps(asdict(t), ensure_ascii=False) + "\n")
    return len(relevant)


def main():
    store = TenderStore(CONFIG["db_path"])

    all_new: List[Tender] = []
    if CONFIG["enable_haicop"]:
        all_new += run_haicop_scraper(store)
    else:
        log.info("HAICOP source disabled (CONFIG['enable_haicop'] = False) - skipping.")

    if CONFIG["enable_wmc"]:
        all_new += run_wmc_scraper(store)
    else:
        log.info("WebManagerCenter source disabled (CONFIG['enable_wmc'] = False) - skipping.")

    exported = export_jsonl(all_new, CONFIG["jsonl_path"])

    log.info("=" * 70)
    log.info(f"Run complete: {len(all_new)} new tenders discovered, "
              f"{exported} passed the OliveSoft software-relevance filter "
              f"(threshold={CONFIG['export_relevance_threshold']}).")
    log.info(f"Database totals: {store.stats()}")
    if exported:
        log.info(f"Relevant tenders appended to: {CONFIG['jsonl_path']}")
    return all_new


if __name__ == "__main__":
    main()